blank_issues_enabled: false
defaults:
  assignees: []
  labels: []
contact_links:
  - name: Documentation
    url: https://github.com/example/hyfuzz-client-ubuntu/wiki
    about: Read the documentation before filing an issue.
