client:
  id: dev-client
  environment: development
protocols:
  enabled_protocols: [coap, modbus]
execution:
  concurrency:
    max_workers: 2
monitoring:
  intervals:
    system: 10
notifications:
  channels:
    console:
      enabled: true
