version: 1
formatters:
  standard:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
root:
  level: INFO
  handlers: [console]
