name: $(echo ${file} | tr '-' ' ' | sed 's/.*/\u&/')
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ${file//-/_}:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Run checks
        run: pytest -q
