name: Release

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish artifacts
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: hyfuzz-client-dist
          path: dist/
